### ISSUE TITLE
Version 2.4 does not work. could  you please make a release from the merged pr that has fixed this

### ISSUE THREAD

**Issue by TheGoofBall64** [KunoichiZ/lumaupdate#91] opened 2021-03-07 07:29 UTC
as the title says. could you please make a release that works. the pr you merged has fixed the breaking issue, just all you need to do is make a release now. could you please do that?

**Comment by Trainax** [comment] 2021-03-07 13:56
See #90

**Comment by TheGoofBall64** [comment] 2021-03-07 16:57
or could you at least make instructions to compile that arent so vague. i cant figure out what you mean by `PATH`, you dont specify where that is. and there is almost nothing you can find online on what to do (at least easily that is). i put the makefile and benertool in the path `lumaupdate-master`  and run make and it says no such file found. i updated ctrulib by replacing all the files in devkitpro with the latest release of ctrulib. and it still doesnt work. you need to say more than three vague bullet points please

**Comment by KunoichiZ** [comment] 2021-03-07 18:51
Closing; duplicate of #90

**Closed as completed by KunoichiZ** 2021-03-07 18:51 UTC
