### ISSUE TITLE
Could not get location header 3xx reply: Ret code: ded92

### ISSUE THREAD

**Issue by daviribeirooliveira** [KunoichiZ/lumaupdate#85] opened 2021-01-24 06:10 UTC
### What model of system are you using?
- [ ] Old 3DS
- [ ] Old 3DS XL
- [ ] 2DS (non-XL)
- [ ] New 3DS
- [x] New 3DS XL
- [ ] New 2DS XL

### What is your current Luma3DS version?
If you are running an hourly version of Luma3DS, please manually update to a stable version as I will no longer deal with people who are using hourlies.

- [ ] Luma3DS v7.1 + boot9strap v1.0/v1.1
- [ ] Luma3DS v8.0 + boot9strap v1.2+
- [ ] Luma3DS v8.1 + boot9strap v1.2+
- [ ] Luma3DS v8.1.1 + boot9strap v1.2+
- [ ] Luma3DS v9.0 + boot9strap v1.2+
- [ ] Luma3DS v9.1 + boot9strap v1.2+
- [x] Luma3DS v10.0+ + boot9strap v1.2+

### What version of Luma Updater are you using?
- [ ] v2.0
- [ ] v2.1
- [ ] v2.1.1
- [ ] v2.1.2
- [ ] v2.2
- [ ] v2.3
- [ ] v2.4
- [x] v2.5

### How are you running Luma Updater?
- [x] .cia
- [ ] .3dsx + HBL/Rosalina

### What problems are you experiencing?

Trying to use luma updater i first get the error:

Could not get location header 3xx reply: Ret code: ded92

![Screenshot_20210124-025252~2](https://user-images.githubusercontent.com/19349637/105622367-d8c09a00-5def-11eb-94f4-940f6fe32846.png)

Then the next screen shows the following:

Could not obtain update details. 
Check that the console is connected to the internet. 

![Screenshots_2021-01-24-02-53-59](https://user-images.githubusercontent.com/19349637/105622375-e37b2f00-5def-11eb-8609-297abe9d3e48.png)

I already tried to update everything, luma manually, boot9strap, godmod, system update, homebrew installer, FBI. I don't know what else can i try, please help. I thank you in advance for you patience and attention. 

### What is the exact error code you are receiving?

Could not get location header 3xx reply: Ret code: ded92

Could not obtain update details. 
Check that the console is connected to the internet. 

### Steps to reproduce

1. Install luma updater using FBI. 
2. Open luma updater. 
3. Receive the error. 

Vídeo of the process:[Installing and opening luma updater ](https://drive.google.com/file/d/1U9QmrHWcz5--3eyJGsjPiZAY3RNm7hoq/view?usp=drivesdk)

**Comment by gio54man87** [comment] 2021-01-27 21:53
im having the same issue as well is there any way to fix it and im using the same exact version he is on for luma3ds luma updater i have the new nintendo 3ds xl and the same bs9 and im booting it up with the cia version

**Comment by sdsnatcher73** [comment] 2021-01-28 17:12
I experience the same issue, currently on Luma3DS 10.2 and lumaupdater 2.5 (cia version, just reinstalled)

**Comment by goldeneyeonline** [comment] 2021-01-30 00:26
This is a duplicate of #82
Yes, 2.5 doesn't work right now.
The other issue suggests going back to 2.4

**Comment by daviribe** [comment] 2021-01-30 00:45
Temporary solution on [#82](https://github.com/KunoichiZ/lumaupdate/issues/82)

**Closed as completed by daviribe** 2021-01-30 00:45 UTC
