### ISSUE TITLE
Luma Updater v2.5 cannot obtain update details

### ISSUE THREAD

**Issue by ericlered** [KunoichiZ/lumaupdate#83] opened 2021-01-12 22:32 UTC
### What model of system are you using?
- [ ] Old 3DS
- [ ] Old 3DS XL
- [ ] 2DS (non-XL)
- [ ] New 3DS
- [ ] New 3DS XL
- [x ] New 2DS XL

### What is your current Luma3DS version?
If you are running an hourly version of Luma3DS, please manually update to a stable version as I will no longer deal with people who are using hourlies.

- [ ] Luma3DS v7.1 + boot9strap v1.0/v1.1
- [ ] Luma3DS v8.0 + boot9strap v1.2+
- [ ] Luma3DS v8.1 + boot9strap v1.2+
- [ ] Luma3DS v8.1.1 + boot9strap v1.2+
- [ ] Luma3DS v9.0 + boot9strap v1.2+
- [ ] Luma3DS v9.1 + boot9strap v1.2+
- [x ] Luma3DS v10.0+ + boot9strap v1.2+

### What version of Luma Updater are you using?
- [ ] v2.0
- [ ] v2.1
- [ ] v2.1.1
- [ ] v2.1.2
- [ ] v2.2
- [ ] v2.3
- [ ] v2.4
- [ x] v2.5

### How are you running Luma Updater?
- [x ] .cia
- [ ] .3dsx + HBL/Rosalina

### What problems are you experiencing?
Please tell us what problems you are facing.

After installing v2.5 with FBI usng the cia I tried running the updater but I get the error message "cannot obtain update details, please check you are connected to the internet"

I am already connected to the internet so that cannot be the issue.

I updte Luma3ds manually to 10.2.1 and have this error, I also had the error before i did this update and was on Luma 9.1

### What is the exact error code you are receiving?
Please give the exact error code the app gives you.

### Steps to reproduce

1. 
2. 
3.

**Comment by KunoichiZ** [comment] 2021-01-12 22:45
Closing; duplicate of #82.

**Closed as completed by KunoichiZ** 2021-01-12 22:45 UTC
